### ISSUE TITLE
Implement worker reading input files

### ISSUE THREAD

**Issue by JeongHunP** [jyhong1/332project#11]
@daehuikim

**Comment by daehuikim** [comment]
@jyhong1 

Work flow
0. Server(Master) run => Client(Worker) run
1. From VM01(Master machine) generate input file
2. Set division size ex)10GB per worker
3. Read input until division size & client(Worker) get that data(Seq)
4. Client(Workers:VM03-VM10) write data on their directories
5. Done

**Comment by daehuikim** [comment]
Done
